"""attendance photos

Revision ID: 0de9ca352231
Revises: 53edaa190cfc
Create Date: 2026-06-07 21:51:16.292996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0de9ca352231'
down_revision = '53edaa190cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('check_out_photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('check_out_photo')
        batch_op.drop_column('check_in_photo')

    # ### end Alembic commands ###
