"""DynamicAttendance extra fields

Revision ID: 1a4872df1b70
Revises: 6a072a2466b6
Create Date: 2026-06-20 14:12:23.061177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4872df1b70'
down_revision = '6a072a2466b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_break', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_break_per_day', ['user_id', 'attendance_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_break', schema=None) as batch_op:
        batch_op.drop_constraint('uq_break_per_day', type_='unique')

    # ### end Alembic commands ###
