"""attendance gps fields

Revision ID: 670c7db1e80f
Revises: 0de9ca352231
Create Date: 2026-06-07 23:57:51.466088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670c7db1e80f'
down_revision = '0de9ca352231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_in_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_out_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('check_out_longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('check_out_longitude')
        batch_op.drop_column('check_out_latitude')
        batch_op.drop_column('check_in_longitude')
        batch_op.drop_column('check_in_latitude')

    # ### end Alembic commands ###
