"""DynamicAttendance extra fields

Revision ID: 6a072a2466b6
Revises: aa2b2dadc1c7
Create Date: 2026-06-20 08:07:46.399287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a072a2466b6'
down_revision = 'aa2b2dadc1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'unit_locations', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dynamic_attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('distance')
        batch_op.drop_column('remarks')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
