"""add distance and remarks to field attendance

Revision ID: a4691008bd01
Revises: f0cdac6a8cfe
Create Date: 2026-06-10 18:00:23.110191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4691008bd01'
down_revision = 'f0cdac6a8cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('distance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_attendance', schema=None) as batch_op:
        batch_op.drop_column('distance')
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
