"""add browser device os to audit logs

Revision ID: d135154032a0
Revises: 670c7db1e80f
Create Date: 2026-06-09 06:02:13.297322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd135154032a0'
down_revision = '670c7db1e80f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('browser', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('device', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('operating_system', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('operating_system')
        batch_op.drop_column('device')
        batch_op.drop_column('browser')

    # ### end Alembic commands ###
